# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05955a070fa27a5496833ef200aa8c9793d2249367aa07b9fa9f1c9898c6f3c78cced56fc44c5323403454cd0e404cd43c574056ee99515d9c3c20bf0b1975a7

test:
  secret_key_base: e472c3285d40bb637136b855c679b2699d9768ce7705cb67a957881e2818a3eace7ef7ac22c586b3b4feeaf99e013f11eee34fd17ee23273edafec16fc0c9fa2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
